# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: gauravdevopspg
  template:
    metadata:
      labels:
        app: gauravdevopspg
    spec:
      containers:
      - name: gauravdevopspg
        image: dockergb1/gauravdevopspg:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: default
spec:
  selector:
    app: gauravdevopspg
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
